


all: FEMA


FEMA: 
	cd fortran; make;
	cd c; make;

fortran: 
	cd fortran; 
	make;

c:
	cd c; make


clean:
		cd fortran; make clean;
		cd c; make clean;

veryclean: 
		cd fortran; make veryclean;
		cd c; make veryclean;






